global:
  dist-dirs: &distDirs dist

clean-pkg-json:
  sort-scripts: true

copy-files:
  from:
  - package.json
  - index.d.ts
  - LICENSE
  - CHANGELOG.md
  - README.md
  - src/fixtures
  to: *distDirs
