language: node_js
sudo: false
node_js:
  - stable
  - lts/carbon
  - lts/boron

before_install:
- npm i -g greenkeeper-lockfile
- if [[ $GH_TOKEN ]]; then ./prepare-gpg-key.sh; fi;
- greenkeeper-lockfile-update

install: npm install

script:
  - npm run tslint
  - npm test -- --forbid-only --forbid-pending
after_script: if [[ $GH_TOKEN ]]; then greenkeeper-lockfile-upload; fi;
after_success: cat ./coverage/lcov.info | coveralls

stages:
- Test
- name: Release
  if: branch=master AND type = push

before_cache: rm -rf ./node_modules/.cache
cache:
  directories:
  - node_modules

jobs:
  include:
  - stage: Release
    node_js: stable
    before_install: if [[ $GH_TOKEN ]]; then ./prepare-gpg-key.sh; fi;
    before_script: npm run build
    script: semantic-release
    after_script: []
    after_success: []