language: node_js
sudo: false

before_install:
- npm i -g greenkeeper-lockfile
- if [[ $GH_TOKEN ]]; then ./prepare-gpg-key.sh; fi;
- greenkeeper-lockfile-update

script:
  - npm run tslint
  - npm test -- --forbid-only --forbid-pending
after_script: if [[ $GH_TOKEN ]]; then greenkeeper-lockfile-upload; fi;
after_success: cat ./coverage/lcov.info | coveralls

stages:
- Test
- Release

oldNode: &oldNode
  before_cache: rm -rf ./node_modules/.cache
  cache:
    directories:
    - node_modules

jobs:
  include:
  - node_js: stable
  - <<: *oldNode
    node_js: lts/carbon
  - <<: *oldNode
    node_js: lts/boron
  - if: branch=master
    stage: Release
    node_js: stable
    before_install: if [[ $GH_TOKEN ]]; then ./prepare-gpg-key.sh; fi;
    before_script: npm run build
    script: semantic-release
    after_script: []
    after_success: []