language: node_js
sudo: false
node_js:
  - stable
  - lts/dubnium
  - lts/carbon

before_install:
  - npm i -g greenkeeper-lockfile yarn
  - greenkeeper-lockfile-update

install: yarn install --check-files --ignore-engines

script:
  - yarn run tslint
  - yarn test --forbid-only --forbid-pending
after_script: if [[ $GH_TOKEN ]]; then greenkeeper-lockfile-upload; fi;
after_success: cat ./coverage/lcov.info | coveralls

stages:
  - Test
  - name: Release
    if: branch=master AND type = push AND tag IS blank

before_cache: rm -rf ./node_modules/.cache
cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: Release
      node_js: stable
      before_install: npm i -g yarn
      before_script: yarn run build
      script: semantic-release
      after_script: []
      after_success: []
